import { Profile } from '@/entities/profile/model/types';

// DELETE: Моковые данные для примера
export const profilesData: Profile[] = [
  {
    _id: 'user_1',
    name: 'Алексей Петров',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Москва',
    birthdayDate: '1985-05-15',
    description: 'Senior Frontend Developer с 8-летним опытом',
    likes: ['user_101', 'user_205', 'user_307'],
    createdAt: '2025-01-01T10:00:00Z',
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Управление командой',
      subcategoryId: 'skill_1',
      name: 'Управление IT-проектами',
      description: 'Научу методологиям Agile и Scrum',
      image: ['/skills/business/project-management.jpg'],
      customSkillId: 'custom_skill_1',
    },
    wantsToLearn: [
      {
        category: 'Творчество и искусство',
        subcategory: 'Музыка и звук',
        subcategoryId: 'skill_2',
        name: 'Основы игры на гитаре',
        customSkillId: 'custom_skill_2',
      },
    ],
    category: 'popular',
  },
  {
    _id: 'user_2',
    name: 'Алексей Петров',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Москва',
    birthdayDate: '1985-05-15',
    description: 'Senior Frontend Developer с 8-летним опытом',
    likes: ['user_101', 'user_205', 'user_307'],
    createdAt: '2025-01-01T10:00:00Z',
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Управление командой',
      subcategoryId: 'skill_1',
      name: 'Управление IT-проектами',
      description: 'Научу методологиям Agile и Scrum',
      image: ['/skills/business/project-management.jpg'],
      customSkillId: 'custom_skill_1',
    },
    wantsToLearn: [
      {
        category: 'Творчество и искусство',
        subcategory: 'Музыка и звук',
        subcategoryId: 'skill_2',
        name: 'Основы игры на гитаре',
        customSkillId: 'custom_skill_2',
      },
    ],
    category: 'popular',
  },
  {
    _id: 'user_3',
    name: 'Алексей Петров',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Москва',
    birthdayDate: '1985-05-15',
    description: 'Senior Frontend Developer с 8-летним опытом',
    likes: ['user_101', 'user_205', 'user_307'],
    createdAt: '2025-01-01T10:00:00Z',
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Управление командой',
      subcategoryId: 'skill_1',
      name: 'Управление IT-проектами',
      description: 'Научу методологиям Agile и Scrum',
      image: ['/skills/business/project-management.jpg'],
      customSkillId: 'custom_skill_1',
    },
    wantsToLearn: [
      {
        category: 'Творчество и искусство',
        subcategory: 'Музыка и звук',
        subcategoryId: 'skill_2',
        name: 'Основы игры на гитаре',
        customSkillId: 'custom_skill_2',
      },
    ],
    category: 'popular',
  },
  {
    _id: 'user_4',
    name: 'Алексей Петров',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Москва',
    birthdayDate: '1985-05-15',
    description: 'Senior Frontend Developer с 8-летним опытом',
    likes: ['user_101', 'user_205', 'user_307'],
    createdAt: '2025-01-01T10:00:00Z',
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Управление командой',
      subcategoryId: 'skill_1',
      name: 'Управление IT-проектами',
      description: 'Научу методологиям Agile и Scrum',
      image: ['/skills/business/project-management.jpg'],
      customSkillId: 'custom_skill_1',
    },
    wantsToLearn: [
      {
        category: 'Творчество и искусство',
        subcategory: 'Музыка и звук',
        subcategoryId: 'skill_2',
        name: 'Основы игры на гитаре',
        customSkillId: 'custom_skill_2',
      },
    ],
    category: 'popular',
  },
  {
    _id: 'user_5',
    name: 'Алексей Петров',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Москва',
    birthdayDate: '1985-05-15',
    description: 'Senior Frontend Developer с 8-летним опытом',
    likes: ['user_101', 'user_205', 'user_307'],
    createdAt: '2025-01-01T10:00:00Z',
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Управление командой',
      subcategoryId: 'skill_1',
      name: 'Управление IT-проектами',
      description: 'Научу методологиям Agile и Scrum',
      image: ['/skills/business/project-management.jpg'],
      customSkillId: 'custom_skill_1',
    },
    wantsToLearn: [
      {
        category: 'Творчество и искусство',
        subcategory: 'Музыка и звук',
        subcategoryId: 'skill_2',
        name: 'Основы игры на гитаре',
        customSkillId: 'custom_skill_2',
      },
    ],
    category: 'popular',
  },
  {
    _id: 'user_6',
    name: 'Алексей Петров',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Москва',
    birthdayDate: '1985-05-15',
    description: 'Senior Frontend Developer с 8-летним опытом',
    likes: ['user_101', 'user_205', 'user_307'],
    createdAt: '2025-01-01T10:00:00Z',
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Управление командой',
      subcategoryId: 'skill_1',
      name: 'Управление IT-проектами',
      description: 'Научу методологиям Agile и Scrum',
      image: ['/skills/business/project-management.jpg'],
      customSkillId: 'custom_skill_1',
    },
    wantsToLearn: [
      {
        category: 'Творчество и искусство',
        subcategory: 'Музыка и звук',
        subcategoryId: 'skill_2',
        name: 'Основы игры на гитаре',
        customSkillId: 'custom_skill_2',
      },
    ],
    category: 'popular',
  },
  {
    _id: 'user_7',
    name: 'Мария Иванова',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Санкт-Петербург',
    birthdayDate: '1990-08-22',
    description: 'UI/UX дизайнер в крупной IT-компании',
    likes: ['user_102', 'user_208'],
    createdAt: '2025-02-15T11:30:00Z',
    canTeach: {
      category: 'Творчество и искусство',
      subcategory: 'Фотография',
      subcategoryId: 'skill_3',
      name: 'Figma для начинающих',
      description: 'Основы работы в Figma',
      image: ['/skills/design/figma.jpg'],
      customSkillId: 'custom_skill_3',
    },
    wantsToLearn: [
      {
        category: 'Иностранные языки',
        subcategory: 'Английский',
        subcategoryId: 'skill_4',
        name: 'Английский для дизайнеров',
        customSkillId: 'custom_skill_4',
      },
    ],
    category: 'match',
  },
  {
    _id: 'user_8',
    name: 'Иван Сидоров',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Новосибирск',
    birthdayDate: '1988-03-10',
    description: 'Digital маркетолог, эксперт по SMM',
    likes: ['user_103', 'user_209', 'user_310'],
    createdAt: '2025-03-05T09:15:00Z',
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Маркетинг и реклама',
      subcategoryId: 'skill_5',
      name: 'Продвижение в Instagram',
      description: 'Стратегии контент-маркетинга',
      image: ['/skills/business/smm.jpg'],
      customSkillId: 'custom_skill_5',
    },
    wantsToLearn: [
      {
        category: 'Иностранные языки',
        subcategory: 'Английский',
        subcategoryId: 'skill_6',
        name: 'Деловой английский',
        customSkillId: 'custom_skill_6',
      },
    ],
    category: 'new',
  },
  {
    _id: 'user_9',
    name: 'Иван Сидоров',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Новосибирск',
    birthdayDate: '1988-03-10',
    description: 'Digital маркетолог, эксперт по SMM',
    likes: ['user_103', 'user_209', 'user_310'],
    createdAt: '2025-03-05T09:15:00Z',
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Маркетинг и реклама',
      subcategoryId: 'skill_5',
      name: 'Продвижение в Instagram',
      description: 'Стратегии контент-маркетинга',
      image: ['/skills/business/smm.jpg'],
      customSkillId: 'custom_skill_5',
    },
    wantsToLearn: [
      {
        category: 'Иностранные языки',
        subcategory: 'Английский',
        subcategoryId: 'skill_6',
        name: 'Деловой английский',
        customSkillId: 'custom_skill_6',
      },
    ],
    category: 'new',
  },
  {
    _id: 'user_10',
    name: 'Иван Сидоров',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Новосибирск',
    birthdayDate: '1988-03-10',
    description: 'Digital маркетолог, эксперт по SMM',
    likes: ['user_103', 'user_209', 'user_310'],
    createdAt: '2025-03-05T09:15:00Z',
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Маркетинг и реклама',
      subcategoryId: 'skill_5',
      name: 'Продвижение в Instagram',
      description: 'Стратегии контент-маркетинга',
      image: ['/skills/business/smm.jpg'],
      customSkillId: 'custom_skill_5',
    },
    wantsToLearn: [
      {
        category: 'Иностранные языки',
        subcategory: 'Английский',
        subcategoryId: 'skill_6',
        name: 'Деловой английский',
        customSkillId: 'custom_skill_6',
      },
    ],
    category: 'new',
  },
  {
    _id: 'user_11',
    name: 'Елена Васильева',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Казань',
    birthdayDate: '1992-11-30',
    description: 'Преподаватель английского языка',
    likes: ['user_104', 'user_210'],
    createdAt: '2025-01-20T14:45:00Z',
    canTeach: {
      category: 'Иностранные языки',
      subcategory: 'Английский',
      subcategoryId: 'skill_7',
      name: 'Разговорный английский',
      description: 'Преодоление языкового барьера',
      image: ['/skills/languages/english.jpg'],
      customSkillId: 'custom_skill_7',
    },
    wantsToLearn: [
      {
        category: 'Здоровье и лайфстайл',
        subcategory: 'Йога и медитация',
        subcategoryId: 'skill_8',
        name: 'Хатха-йога для начинающих',
        customSkillId: 'custom_skill_8',
      },
    ],
    category: 'ideas',
  },
  {
    _id: 'user_12',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_13',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_14',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_15',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_16',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_17',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_18',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_19',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_20',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_21',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_22',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_23',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_24',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_25',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_26',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_27',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_28',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_29',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_30',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_31',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_32',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_33',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_34',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_35',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_36',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_37',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_38',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_39',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_40',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_41',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_42',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_43',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_44',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_45',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_46',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_47',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_48',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_49',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_50',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_51',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_52',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_53',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_54',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_55',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_56',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_57',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_58',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_59',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
  {
    _id: 'user_60',
    name: 'Дмитрий Смирнов',
    image:
      'https://avatars.mds.yandex.net/i?id=0eaa142d7202ac9bbd26ac279e7ae159_l-4898876-images-thumbs&n=27&h=480&w=480',
    city: 'Екатеринбург',
    birthdayDate: '1983-07-18',
    description: 'Фитнес-тренер и нутрициолог',
    likes: ['user_105', 'user_211', 'user_312'],
    createdAt: '2025-02-02T16:20:00Z',
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Физические тренировки',
      subcategoryId: 'skill_9',
      name: 'Функциональный тренинг',
      description: 'Тренировки с собственным весом',
      image: ['/skills/health/fitness.jpg'],
      customSkillId: 'custom_skill_9',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Предпринимательство',
        subcategoryId: 'skill_10',
        name: 'Стартапы с нуля',
        customSkillId: 'custom_skill_10',
      },
    ],
    category: 'recommended',
  },
];
