import { Profile } from '@/entities/profile/model/types';

// DELETE: Моковые данные для примера
export const profilesData: Profile[] = [
  {
    id: '1',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'popular',
  },
  {
    id: '2',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'match',
  },
  {
    id: '3',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '4',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '5',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '6',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '7',
    name: 'Иван Сидоров',
    avatar: '',
    canTeach: 'Маркетинг, SMM',
    wantToLearn: 'Английский язык',
    category: 'new',
  },
  {
    id: '8',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '9',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '10',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '11',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '12',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '13',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '14',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '15',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'popular',
  },
  {
    id: '16',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'match',
  },
  {
    id: '17',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '18',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '19',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '20',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '21',
    name: 'Иван Сидоров',
    avatar: '',
    canTeach: 'Маркетинг, SMM',
    wantToLearn: 'Английский язык',
    category: 'new',
  },
  {
    id: '22',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '23',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '24',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '25',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '26',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '27',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '28',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '29',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'popular',
  },
  {
    id: '30',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'match',
  },
  {
    id: '31',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '32',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '33',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '34',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '35',
    name: 'Иван Сидоров',
    avatar: '',
    canTeach: 'Маркетинг, SMM',
    wantToLearn: 'Английский язык',
    category: 'new',
  },
  {
    id: '36',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '37',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '38',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '39',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '40',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '41',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '42',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '43',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'popular',
  },
  {
    id: '44',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'match',
  },
  {
    id: '45',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '46',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '47',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '48',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '49',
    name: 'Иван Сидоров',
    avatar: '',
    canTeach: 'Маркетинг, SMM',
    wantToLearn: 'Английский язык',
    category: 'new',
  },
  {
    id: '50',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '51',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '52',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '53',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '54',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '55',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '56',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '57',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'popular',
  },
  {
    id: '58',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'match',
  },
  {
    id: '59',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '60',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '61',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '62',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '63',
    name: 'Иван Сидоров',
    avatar: '',
    canTeach: 'Маркетинг, SMM',
    wantToLearn: 'Английский язык',
    category: 'new',
  },
  {
    id: '64',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '65',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '66',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '67',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '68',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '69',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '70',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '71',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'popular',
  },
  {
    id: '72',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'match',
  },
  {
    id: '73',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '74',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '75',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '76',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '77',
    name: 'Иван Сидоров',
    avatar: '',
    canTeach: 'Маркетинг, SMM',
    wantToLearn: 'Английский язык',
    category: 'new',
  },
  {
    id: '78',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '79',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '80',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '81',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '82',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '83',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '84',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '85',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'popular',
  },
  {
    id: '86',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'match',
  },
  {
    id: '87',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '88',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '89',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '90',
    name: 'Мария Иванова',
    avatar: '',
    canTeach: 'Дизайн интерфейсов',
    wantToLearn: 'Английский язык',
    category: 'popular',
  },
  {
    id: '91',
    name: 'Иван Сидоров',
    avatar: '',
    canTeach: 'Маркетинг, SMM',
    wantToLearn: 'Английский язык',
    category: 'new',
  },
  {
    id: '92',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '93',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '94',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '95',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '96',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '97',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '98',
    name: 'Елена Васильева',
    avatar: '',
    canTeach: 'Английский язык',
    wantToLearn: 'Французский язык',
    category: 'recommended',
  },
  {
    id: '99',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'popular',
  },
  {
    id: '100',
    name: 'Алексей Петров',
    avatar: '',
    canTeach: 'Программирование на JavaScript',
    wantToLearn: 'Игра на гитаре',
    category: 'match',
  },
];
