import { User } from '@/entities/user/model/types';

export const mockUsers: User[] = [
  {
    _id: 'user_001',
    name: 'Анна Козлова',
    image: 'https://example.com/avatars/anna.jpg',
    city: 'Москва',
    birthdayDate: '1992-03-15',
    description: 'Профессиональный коуч и HR-специалист с 8-летним опытом',
    likes: ['коучинг', 'развитие', 'бизнес'],
    createdAt: new Date(2023, 5, 10),
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Личный бренд',
      subcategoryId: 'bus_coach_001',
      name: 'Карьерный коучинг',
      description: 'Помогаю определить профессиональные цели и составить план развития',
      image: [
        'https://example.com/skills/coaching1.jpg',
        'https://example.com/skills/coaching2.jpg',
      ],
      customSkillId: 'skill_coach_001',
    },
    wantsToLearn: [
      {
        category: 'Иностранные языки',
        subcategory: 'Английский',
        subcategoryId: 'lang_eng_001',
        name: 'Деловой английский',
        customSkillId: 'want_lang_001',
      },
    ],
  },
  {
    _id: 'user_002',
    name: 'Дмитрий Смирнов',
    image: 'https://example.com/avatars/dmitry.jpg',
    city: 'Санкт-Петербург',
    birthdayDate: '1988-07-22',
    description: 'Фотограф с 10-летним опытом, специализация - портретная съемка',
    likes: ['фотография', 'искусство', 'преподавание'],
    createdAt: new Date(2023, 2, 18),
    canTeach: {
      category: 'Творчество и искусство',
      subcategory: 'Фотография',
      subcategoryId: 'art_photo_001',
      name: 'Основы портретной фотографии',
      description: 'Научу работать с естественным светом и строить композицию',
      image: ['https://example.com/skills/photo1.jpg', 'https://example.com/skills/photo2.jpg'],
      customSkillId: 'skill_photo_001',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Личный бренд',
        subcategoryId: 'bus_brand_001',
        name: 'Продвижение в Instagram',
        customSkillId: 'want_brand_001',
      },
      {
        category: 'Здоровье и лайфстайл',
        subcategory: 'Йога и медитация',
        subcategoryId: 'health_yoga_001',
        name: 'Йога для спины',
        customSkillId: 'want_yoga_001',
      },
      {
        category: 'Иностранные языки',
        subcategory: 'Английский',
        subcategoryId: 'lang_eng_001',
        name: 'Деловой английский',
        customSkillId: 'want_lang_001',
      },
    ],
  },
  {
    _id: 'user_003',
    name: 'Ольга Новикова',
    image: 'https://example.com/avatars/olga.jpg',
    city: 'Казань',
    birthdayDate: '1995-11-30',
    description: 'Преподаватель английского языка с сертификатом CELTA',
    likes: ['английский', 'преподавание', 'путешествия'],
    createdAt: new Date(2023, 1, 5),
    canTeach: {
      category: 'Иностранные языки',
      subcategory: 'Английский',
      subcategoryId: 'lang_eng_002',
      name: 'Английский для путешествий',
      description: 'Практические фразы и лайфхаки для комфортных поездок',
      image: ['https://example.com/skills/english1.jpg', 'https://example.com/skills/english2.jpg'],
      customSkillId: 'skill_eng_001',
    },
    wantsToLearn: [
      {
        category: 'Дом и уют',
        subcategory: 'Приготовление еды',
        subcategoryId: 'home_cook_001',
        name: 'Итальянская кухня',
        customSkillId: 'want_cook_001',
      },
    ],
  },
  {
    _id: 'user_004',
    name: 'Иван Петров',
    image: 'https://example.com/avatars/ivan.jpg',
    city: 'Новосибирск',
    birthdayDate: '1990-09-12',
    description: 'Профессиональный повар, специалист по итальянской кухне',
    likes: ['кулинария', 'италия', 'обучение'],
    createdAt: new Date(2023, 4, 22),
    canTeach: {
      category: 'Дом и уют',
      subcategory: 'Приготовление еды',
      subcategoryId: 'home_cook_002',
      name: 'Паста ручной работы',
      description: 'Научу готовить 5 видов традиционной итальянской пасты',
      image: ['https://example.com/skills/pasta1.jpg', 'https://example.com/skills/pasta2.jpg'],
      customSkillId: 'skill_cook_001',
    },
    wantsToLearn: [
      {
        category: 'Иностранные языки',
        subcategory: 'Испанский',
        subcategoryId: 'lang_ita_001',
        name: 'Базовый итальянский',
        customSkillId: 'want_ita_001',
      },
    ],
  },
  {
    _id: 'user_005',
    name: 'Екатерина Волкова',
    image: 'https://example.com/avatars/ekaterina.jpg',
    city: 'Сочи',
    birthdayDate: '1987-04-05',
    description: 'Сертифицированный инструктор по йоге и медитации',
    likes: ['йога', 'медитация', 'зож'],
    createdAt: new Date(2023, 3, 15),
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Йога и медитация',
      subcategoryId: 'health_yoga_002',
      name: 'Хатха-йога для начинающих',
      description: 'Базовые асаны и принципы правильного дыхания',
      image: ['https://example.com/skills/yoga1.jpg', 'https://example.com/skills/yoga2.jpg'],
      customSkillId: 'skill_yoga_001',
    },
    wantsToLearn: [
      {
        category: 'Образование и развитие',
        subcategory: 'Навыки преподавания',
        subcategoryId: 'edu_teach_001',
        name: 'Методики онлайн-обучения',
        customSkillId: 'want_teach_001',
      },
    ],
  },
  {
    _id: 'user_001',
    name: 'Анна Козлова',
    image: 'https://example.com/avatars/anna.jpg',
    city: 'Москва',
    birthdayDate: '1992-03-15',
    description: 'Профессиональный коуч и HR-специалист с 8-летним опытом',
    likes: ['коучинг', 'развитие', 'бизнес'],
    createdAt: new Date(2023, 5, 10),
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Личный бренд',
      subcategoryId: 'bus_coach_001',
      name: 'Карьерный коучинг',
      description: 'Помогаю определить профессиональные цели и составить план развития',
      image: [
        'https://example.com/skills/coaching1.jpg',
        'https://example.com/skills/coaching2.jpg',
      ],
      customSkillId: 'skill_coach_001',
    },
    wantsToLearn: [
      {
        category: 'Иностранные языки',
        subcategory: 'Английский',
        subcategoryId: 'lang_eng_001',
        name: 'Деловой английский',
        customSkillId: 'want_lang_001',
      },
    ],
  },
  {
    _id: 'user_002',
    name: 'Дмитрий Смирнов',
    image: 'https://example.com/avatars/dmitry.jpg',
    city: 'Санкт-Петербург',
    birthdayDate: '1988-07-22',
    description: 'Фотограф с 10-летним опытом, специализация - портретная съемка',
    likes: ['фотография', 'искусство', 'преподавание'],
    createdAt: new Date(2023, 2, 18),
    canTeach: {
      category: 'Творчество и искусство',
      subcategory: 'Фотография',
      subcategoryId: 'art_photo_001',
      name: 'Основы портретной фотографии',
      description: 'Научу работать с естественным светом и строить композицию',
      image: ['https://example.com/skills/photo1.jpg', 'https://example.com/skills/photo2.jpg'],
      customSkillId: 'skill_photo_001',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Личный бренд',
        subcategoryId: 'bus_brand_001',
        name: 'Продвижение в Instagram',
        customSkillId: 'want_brand_001',
      },
      {
        category: 'Здоровье и лайфстайл',
        subcategory: 'Йога и медитация',
        subcategoryId: 'health_yoga_001',
        name: 'Йога для спины',
        customSkillId: 'want_yoga_001',
      },
      {
        category: 'Иностранные языки',
        subcategory: 'Английский',
        subcategoryId: 'lang_eng_001',
        name: 'Деловой английский',
        customSkillId: 'want_lang_001',
      },
    ],
  },
  {
    _id: 'user_003',
    name: 'Ольга Новикова',
    image: 'https://example.com/avatars/olga.jpg',
    city: 'Казань',
    birthdayDate: '1995-11-30',
    description: 'Преподаватель английского языка с сертификатом CELTA',
    likes: ['английский', 'преподавание', 'путешествия'],
    createdAt: new Date(2023, 1, 5),
    canTeach: {
      category: 'Иностранные языки',
      subcategory: 'Английский',
      subcategoryId: 'lang_eng_002',
      name: 'Английский для путешествий',
      description: 'Практические фразы и лайфхаки для комфортных поездок',
      image: ['https://example.com/skills/english1.jpg', 'https://example.com/skills/english2.jpg'],
      customSkillId: 'skill_eng_001',
    },
    wantsToLearn: [
      {
        category: 'Дом и уют',
        subcategory: 'Приготовление еды',
        subcategoryId: 'home_cook_001',
        name: 'Итальянская кухня',
        customSkillId: 'want_cook_001',
      },
    ],
  },
  {
    _id: 'user_004',
    name: 'Иван Петров',
    image: 'https://example.com/avatars/ivan.jpg',
    city: 'Новосибирск',
    birthdayDate: '1990-09-12',
    description: 'Профессиональный повар, специалист по итальянской кухне',
    likes: ['кулинария', 'италия', 'обучение'],
    createdAt: new Date(2023, 4, 22),
    canTeach: {
      category: 'Дом и уют',
      subcategory: 'Приготовление еды',
      subcategoryId: 'home_cook_002',
      name: 'Паста ручной работы',
      description: 'Научу готовить 5 видов традиционной итальянской пасты',
      image: ['https://example.com/skills/pasta1.jpg', 'https://example.com/skills/pasta2.jpg'],
      customSkillId: 'skill_cook_001',
    },
    wantsToLearn: [
      {
        category: 'Иностранные языки',
        subcategory: 'Испанский',
        subcategoryId: 'lang_ita_001',
        name: 'Базовый итальянский',
        customSkillId: 'want_ita_001',
      },
    ],
  },
  {
    _id: 'user_005',
    name: 'Екатерина Волкова',
    image: 'https://example.com/avatars/ekaterina.jpg',
    city: 'Сочи',
    birthdayDate: '1987-04-05',
    description: 'Сертифицированный инструктор по йоге и медитации',
    likes: ['йога', 'медитация', 'зож'],
    createdAt: new Date(2023, 3, 15),
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Йога и медитация',
      subcategoryId: 'health_yoga_002',
      name: 'Хатха-йога для начинающих',
      description: 'Базовые асаны и принципы правильного дыхания',
      image: ['https://example.com/skills/yoga1.jpg', 'https://example.com/skills/yoga2.jpg'],
      customSkillId: 'skill_yoga_001',
    },
    wantsToLearn: [
      {
        category: 'Образование и развитие',
        subcategory: 'Навыки преподавания',
        subcategoryId: 'edu_teach_001',
        name: 'Методики онлайн-обучения',
        customSkillId: 'want_teach_001',
      },
    ],
  },
  {
    _id: 'user_001',
    name: 'Анна Козлова',
    image: 'https://example.com/avatars/anna.jpg',
    city: 'Москва',
    birthdayDate: '1992-03-15',
    description: 'Профессиональный коуч и HR-специалист с 8-летним опытом',
    likes: ['коучинг', 'развитие', 'бизнес'],
    createdAt: new Date(2023, 5, 10),
    canTeach: {
      category: 'Бизнес и карьера',
      subcategory: 'Личный бренд',
      subcategoryId: 'bus_coach_001',
      name: 'Карьерный коучинг',
      description: 'Помогаю определить профессиональные цели и составить план развития',
      image: [
        'https://example.com/skills/coaching1.jpg',
        'https://example.com/skills/coaching2.jpg',
      ],
      customSkillId: 'skill_coach_001',
    },
    wantsToLearn: [
      {
        category: 'Иностранные языки',
        subcategory: 'Английский',
        subcategoryId: 'lang_eng_001',
        name: 'Деловой английский',
        customSkillId: 'want_lang_001',
      },
    ],
  },
  {
    _id: 'user_002',
    name: 'Дмитрий Смирнов',
    image: 'https://example.com/avatars/dmitry.jpg',
    city: 'Санкт-Петербург',
    birthdayDate: '1988-07-22',
    description: 'Фотограф с 10-летним опытом, специализация - портретная съемка',
    likes: ['фотография', 'искусство', 'преподавание'],
    createdAt: new Date(2023, 2, 18),
    canTeach: {
      category: 'Творчество и искусство',
      subcategory: 'Фотография',
      subcategoryId: 'art_photo_001',
      name: 'Основы портретной фотографии',
      description: 'Научу работать с естественным светом и строить композицию',
      image: ['https://example.com/skills/photo1.jpg', 'https://example.com/skills/photo2.jpg'],
      customSkillId: 'skill_photo_001',
    },
    wantsToLearn: [
      {
        category: 'Бизнес и карьера',
        subcategory: 'Личный бренд',
        subcategoryId: 'bus_brand_001',
        name: 'Продвижение в Instagram',
        customSkillId: 'want_brand_001',
      },
      {
        category: 'Здоровье и лайфстайл',
        subcategory: 'Йога и медитация',
        subcategoryId: 'health_yoga_001',
        name: 'Йога для спины',
        customSkillId: 'want_yoga_001',
      },
      {
        category: 'Иностранные языки',
        subcategory: 'Английский',
        subcategoryId: 'lang_eng_001',
        name: 'Деловой английский',
        customSkillId: 'want_lang_001',
      },
    ],
  },
  {
    _id: 'user_003',
    name: 'Ольга Новикова',
    image: 'https://example.com/avatars/olga.jpg',
    city: 'Казань',
    birthdayDate: '1995-11-30',
    description: 'Преподаватель английского языка с сертификатом CELTA',
    likes: ['английский', 'преподавание', 'путешествия'],
    createdAt: new Date(2023, 1, 5),
    canTeach: {
      category: 'Иностранные языки',
      subcategory: 'Английский',
      subcategoryId: 'lang_eng_002',
      name: 'Английский для путешествий',
      description: 'Практические фразы и лайфхаки для комфортных поездок',
      image: ['https://example.com/skills/english1.jpg', 'https://example.com/skills/english2.jpg'],
      customSkillId: 'skill_eng_001',
    },
    wantsToLearn: [
      {
        category: 'Дом и уют',
        subcategory: 'Приготовление еды',
        subcategoryId: 'home_cook_001',
        name: 'Итальянская кухня',
        customSkillId: 'want_cook_001',
      },
    ],
  },
  {
    _id: 'user_004',
    name: 'Иван Петров',
    image: 'https://example.com/avatars/ivan.jpg',
    city: 'Новосибирск',
    birthdayDate: '1990-09-12',
    description: 'Профессиональный повар, специалист по итальянской кухне',
    likes: ['кулинария', 'италия', 'обучение'],
    createdAt: new Date(2023, 4, 22),
    canTeach: {
      category: 'Дом и уют',
      subcategory: 'Приготовление еды',
      subcategoryId: 'home_cook_002',
      name: 'Паста ручной работы',
      description: 'Научу готовить 5 видов традиционной итальянской пасты',
      image: ['https://example.com/skills/pasta1.jpg', 'https://example.com/skills/pasta2.jpg'],
      customSkillId: 'skill_cook_001',
    },
    wantsToLearn: [
      {
        category: 'Иностранные языки',
        subcategory: 'Испанский',
        subcategoryId: 'lang_ita_001',
        name: 'Базовый итальянский',
        customSkillId: 'want_ita_001',
      },
    ],
  },
  {
    _id: 'user_005',
    name: 'Екатерина Волкова',
    image: 'https://example.com/avatars/ekaterina.jpg',
    city: 'Сочи',
    birthdayDate: '1987-04-05',
    description: 'Сертифицированный инструктор по йоге и медитации',
    likes: ['йога', 'медитация', 'зож'],
    createdAt: new Date(2023, 3, 15),
    canTeach: {
      category: 'Здоровье и лайфстайл',
      subcategory: 'Йога и медитация',
      subcategoryId: 'health_yoga_002',
      name: 'Хатха-йога для начинающих',
      description: 'Базовые асаны и принципы правильного дыхания',
      image: ['https://example.com/skills/yoga1.jpg', 'https://example.com/skills/yoga2.jpg'],
      customSkillId: 'skill_yoga_001',
    },
    wantsToLearn: [
      {
        category: 'Образование и развитие',
        subcategory: 'Навыки преподавания',
        subcategoryId: 'edu_teach_001',
        name: 'Методики онлайн-обучения',
        customSkillId: 'want_teach_001',
      },
    ],
  },
];
